### ISSUE TITLE
Any possibility of support for older Jenkins versions?

### ISSUE THREAD

**Issue by brucekaskel** [jenkinsci/add-changes-to-build-changelog-plugin#8]
### What feature do you want to see added?

My company uses an older version of Jenkins at this time. Much older. 2.303. It is not in my control to update this.
If there was any way for this plugin to support older versions I would definitely use it.
If that is not possible, I understand. Thank you.

**Comment by danielomoto** [comment]
Hi, Brucekaskel!  Thanks for the ticket!  I really appreicate it.

That's a really good suggestion about supporting older versions.   I assume there is a way to update the plugin to support really older versions (like 2.303), but I'm not quite for sure how to do it (this is my first plugin 😄).  That being said, the plugin itself is really trivial on what it's doing under the hood.  You could do something identical with a few lines of code if you had access to the jenkins model/api and the jenkins file system.  Are those things something you have access to?  

If so, you would just need to update the changelog.xml file (located in the build directory) and then reload the build in question from disk.  For example, you could:

1. copy and paste the xml contents from an existing changelog and format them to suite your new build's changes.. 
2. call the reload endpoint from the jenkins rest api (e.g.  myjenkinsurl.com/job/myjob/build/1234/reload via curl) or if you like to do it via the jenkins model, you can use the [reload](https://javadoc.jenkins-ci.org/hudson/model/Run.html#reload()) endpoint after getting the build from something like [getBuildByNumber](https://javadoc.jenkins-ci.org/hudson/model/abstractproject.html#getBuildByNumber(int)).

This can be done in a build step (if you're using a freestylebuild) or a pipeline.

Would that work for you?

**Comment by brucekaskel** [comment]
Thanks for your response.

I found this page: https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/

However this page clearly says that plugins should not be built for versions older than "2.364 for weekly releases, and 2.361.1 for LTS release" at this time. 

So I now realize you cannot support my version of Jenkins. Thank you anyway. Maybe in the future I will be able to use this plugin when I am using a newer version of Jenkins.

Please feel free to close this Issue.

**Comment by danielomoto** [comment]
Thanks for finding that article and letting me know the policy that plugins should follow in terms of old releases.  Very informative!  I'll close the issue like you said.  I hope you find a way to accomplish what you want to do. 😄
